services:
  app:
    build:
      context: .
      target: dev
    ports:
      - "8000:8000"
    environment:
      - ENV=dev
    volumes:
      - venv_cache:/app/.venv
    develop:
      watch:
        - path: .
          action: sync
          target: /app
    depends_on:
      - db

  db:
    image: postgres:17
    ports:
      - "5432:5432"
    env_file:
      - ./db.env
    volumes:
      - db_data:/var/lib/postgresql/data

  test:
    profiles:
      - test
    build:
      context: .
      target: dev
    command: uv run pytest -v
    volumes:
      - .:/app
    depends_on:
      - db

volumes:
  venv_cache:
  db_data: