"""add cast rules

Revision ID: 02f269a5918b
Revises: 45631bae610f
Create Date: 2025-11-14 17:40:52.408634

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "02f269a5918b"
down_revision: Union[str, Sequence[str], None] = "45631bae610f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum type explicitly
    castsafety_enum = postgresql.ENUM(
        "IMPLICIT", "SAFE", "UNSAFE", name="castsafety", create_type=False
    )
    castsafety_enum.create(op.get_bind(), checkfirst=True)

    op.create_table(
        "cast_rules",
        sa.Column("source_data_type_id", sa.UUID(), nullable=False),
        sa.Column("target_data_type_id", sa.UUID(), nullable=False),
        sa.Column(
            "param_mapping", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("safety", castsafety_enum, nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_data_type_id"],
            ["data_types.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_data_type_id"],
            ["data_types.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source_data_type_id",
            "target_data_type_id",
            name="idx_cast_rule_source_target_data_type_id",
        ),
    )
    op.create_index(
        op.f("ix_cast_rules_created_by"), "cast_rules", ["created_by"], unique=False
    )
    op.create_index(op.f("ix_cast_rules_id"), "cast_rules", ["id"], unique=True)
    op.create_index(
        op.f("ix_cast_rules_updated_by"), "cast_rules", ["updated_by"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_cast_rules_updated_by"), table_name="cast_rules")
    op.drop_index(op.f("ix_cast_rules_id"), table_name="cast_rules")
    op.drop_index(op.f("ix_cast_rules_created_by"), table_name="cast_rules")
    op.drop_table("cast_rules")
    # Drop enum type
    castsafety_enum = postgresql.ENUM(
        "IMPLICIT", "SAFE", "UNSAFE", name="castsafety", create_type=True
    )
    castsafety_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
