"""use nullable mixin

Revision ID: 107422516b88
Revises: 031f8caaf603
Create Date: 2025-11-08 11:46:35.652545

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "107422516b88"
down_revision: Union[str, Sequence[str], None] = "031f8caaf603"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "created_by", existing_type=sa.UUID(), nullable=True)
    op.alter_column("users", "updated_by", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "updated_by", existing_type=sa.UUID(), nullable=False)
    op.alter_column("users", "created_by", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###
