"""add system kind

Revision ID: 2780f975a786
Revises: d69abe67dae2
Create Date: 2025-11-11 07:04:40.835934

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2780f975a786"
down_revision: Union[str, Sequence[str], None] = "d69abe67dae2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "system_kinds",
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_system_kinds_code"), "system_kinds", ["code"], unique=True)
    op.create_index(
        op.f("ix_system_kinds_created_by"), "system_kinds", ["created_by"], unique=False
    )
    op.create_index(op.f("ix_system_kinds_id"), "system_kinds", ["id"], unique=True)
    op.create_index(
        op.f("ix_system_kinds_updated_by"), "system_kinds", ["updated_by"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_system_kinds_updated_by"), table_name="system_kinds")
    op.drop_index(op.f("ix_system_kinds_id"), table_name="system_kinds")
    op.drop_index(op.f("ix_system_kinds_created_by"), table_name="system_kinds")
    op.drop_index(op.f("ix_system_kinds_code"), table_name="system_kinds")
    op.drop_table("system_kinds")
    # ### end Alembic commands ###
