"""add field_binding

Revision ID: 3d4daf44f3fa
Revises: f062a145c6b4
Create Date: 2025-11-15 14:57:46.563337

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3d4daf44f3fa"
down_revision: Union[str, Sequence[str], None] = "f062a145c6b4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "field_bindings",
        sa.Column("field_id", sa.UUID(), nullable=False),
        sa.Column("dataset_schema_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("is_nullable", sa.Boolean(), nullable=False),
        sa.Column("data_type_id", sa.UUID(), nullable=False),
        sa.Column(
            "type_params", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["data_type_id"],
            ["data_types.id"],
        ),
        sa.ForeignKeyConstraint(
            ["dataset_schema_id"],
            ["dataset_schemas.id"],
        ),
        sa.ForeignKeyConstraint(
            ["field_id"],
            ["fields.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "dataset_schema_id",
            "field_id",
            name="idx_field_binding_dataset_schema_id_field_id",
        ),
        sa.UniqueConstraint(
            "dataset_schema_id",
            "position",
            name="idx_field_binding_dataset_schema_id_position",
        ),
    )
    op.create_index(
        op.f("ix_field_bindings_created_by"),
        "field_bindings",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_field_bindings_data_type_id"),
        "field_bindings",
        ["data_type_id"],
        unique=False,
    )
    op.create_index(op.f("ix_field_bindings_id"), "field_bindings", ["id"], unique=True)
    op.create_index(
        op.f("ix_field_bindings_updated_by"),
        "field_bindings",
        ["updated_by"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_field_bindings_updated_by"), table_name="field_bindings")
    op.drop_index(op.f("ix_field_bindings_id"), table_name="field_bindings")
    op.drop_index(op.f("ix_field_bindings_data_type_id"), table_name="field_bindings")
    op.drop_index(op.f("ix_field_bindings_created_by"), table_name="field_bindings")
    op.drop_table("field_bindings")
    # ### end Alembic commands ###
