"""add uq and bk into model

Revision ID: 45631bae610f
Revises: 762b12bd12af
Create Date: 2025-11-14 16:58:40.220634

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "45631bae610f"
down_revision: Union[str, Sequence[str], None] = "762b12bd12af"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "dataset_hive",
        sa.Column(
            "bkey_columns", postgresql.ARRAY(sa.String(length=255)), nullable=True
        ),
    )
    op.add_column(
        "dataset_rdbms",
        sa.Column(
            "uq_constraints", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("dataset_rdbms", "uq_constraints")
    op.drop_column("dataset_hive", "bkey_columns")
    # ### end Alembic commands ###
