"""add data type

Revision ID: 4ad1f4877a24
Revises: b06e5202aa44
Create Date: 2025-11-11 15:35:26.553454

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4ad1f4877a24"
down_revision: Union[str, Sequence[str], None] = "b06e5202aa44"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_types",
        sa.Column("system_flavor_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column(
            "params_schema", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("render_template", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["system_flavor_id"],
            ["system_flavors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "system_flavor_id", "code", name="idx_data_type_system_flavor_id_code"
        ),
    )
    op.create_index(
        op.f("ix_data_types_created_by"), "data_types", ["created_by"], unique=False
    )
    op.create_index(op.f("ix_data_types_id"), "data_types", ["id"], unique=True)
    op.create_index(
        op.f("ix_data_types_updated_by"), "data_types", ["updated_by"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_data_types_updated_by"), table_name="data_types")
    op.drop_index(op.f("ix_data_types_id"), table_name="data_types")
    op.drop_index(op.f("ix_data_types_created_by"), table_name="data_types")
    op.drop_table("data_types")
    # ### end Alembic commands ###
