"""add CrawlRun model

Revision ID: 85e55c3a1a5f
Revises: 03df15a0f6ce
Create Date: 2026-04-14 10:22:22.514842

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "85e55c3a1a5f"
down_revision: Union[str, Sequence[str], None] = "03df15a0f6ce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "crawl_runs",
        sa.Column("system_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("summary", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "row_version", sa.Integer(), server_default=sa.text("1"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["system_id"],
            ["systems.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_crawl_runs_created_by"), "crawl_runs", ["created_by"], unique=False
    )
    op.create_index(op.f("ix_crawl_runs_id"), "crawl_runs", ["id"], unique=True)
    op.create_index(
        op.f("ix_crawl_runs_updated_by"), "crawl_runs", ["updated_by"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_crawl_runs_updated_by"), table_name="crawl_runs")
    op.drop_index(op.f("ix_crawl_runs_id"), table_name="crawl_runs")
    op.drop_index(op.f("ix_crawl_runs_created_by"), table_name="crawl_runs")
    op.drop_table("crawl_runs")
    # ### end Alembic commands ###
