"""initial migration

Revision ID: 8a94827257da
Revises:
Create Date: 2025-11-13 17:26:19.265814

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8a94827257da"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "credential_refs",
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("path", sa.String(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "provider", "path", name="idx_credential_ref_provider_path"
        ),
    )
    op.create_index(
        op.f("ix_credential_refs_created_by"),
        "credential_refs",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_credential_refs_id"), "credential_refs", ["id"], unique=True
    )
    op.create_index(
        op.f("ix_credential_refs_updated_by"),
        "credential_refs",
        ["updated_by"],
        unique=False,
    )
    op.create_table(
        "system_kinds",
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_system_kinds_code"), "system_kinds", ["code"], unique=True)
    op.create_index(
        op.f("ix_system_kinds_created_by"), "system_kinds", ["created_by"], unique=False
    )
    op.create_index(op.f("ix_system_kinds_id"), "system_kinds", ["id"], unique=True)
    op.create_index(
        op.f("ix_system_kinds_updated_by"), "system_kinds", ["updated_by"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_created_by"), "users", ["created_by"], unique=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=True)
    op.create_index(op.f("ix_users_updated_by"), "users", ["updated_by"], unique=False)
    op.create_table(
        "system_flavors",
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("vendor", sa.String(), nullable=True),
        sa.Column("versions", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("kind_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["kind_id"],
            ["system_kinds.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_system_flavors_code"), "system_flavors", ["code"], unique=True
    )
    op.create_index(
        op.f("ix_system_flavors_created_by"),
        "system_flavors",
        ["created_by"],
        unique=False,
    )
    op.create_index(op.f("ix_system_flavors_id"), "system_flavors", ["id"], unique=True)
    op.create_index(
        op.f("ix_system_flavors_updated_by"),
        "system_flavors",
        ["updated_by"],
        unique=False,
    )
    op.create_table(
        "data_types",
        sa.Column("system_flavor_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column(
            "params_schema", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("render_template", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["system_flavor_id"],
            ["system_flavors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "system_flavor_id", "code", name="idx_data_type_system_flavor_id_code"
        ),
    )
    op.create_index(
        op.f("ix_data_types_created_by"), "data_types", ["created_by"], unique=False
    )
    op.create_index(op.f("ix_data_types_id"), "data_types", ["id"], unique=True)
    op.create_index(
        op.f("ix_data_types_updated_by"), "data_types", ["updated_by"], unique=False
    )
    op.create_table(
        "systems",
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("tags", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("extra", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("flavor_id", sa.UUID(), nullable=False),
        sa.Column("credential_ref_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["credential_ref_id"],
            ["credential_refs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["flavor_id"],
            ["system_flavors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_systems_code"), "systems", ["code"], unique=True)
    op.create_index(
        op.f("ix_systems_created_by"), "systems", ["created_by"], unique=False
    )
    op.create_index(op.f("ix_systems_id"), "systems", ["id"], unique=True)
    op.create_index(
        op.f("ix_systems_updated_by"), "systems", ["updated_by"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_systems_updated_by"), table_name="systems")
    op.drop_index(op.f("ix_systems_id"), table_name="systems")
    op.drop_index(op.f("ix_systems_created_by"), table_name="systems")
    op.drop_index(op.f("ix_systems_code"), table_name="systems")
    op.drop_table("systems")
    op.drop_index(op.f("ix_data_types_updated_by"), table_name="data_types")
    op.drop_index(op.f("ix_data_types_id"), table_name="data_types")
    op.drop_index(op.f("ix_data_types_created_by"), table_name="data_types")
    op.drop_table("data_types")
    op.drop_index(op.f("ix_system_flavors_updated_by"), table_name="system_flavors")
    op.drop_index(op.f("ix_system_flavors_id"), table_name="system_flavors")
    op.drop_index(op.f("ix_system_flavors_created_by"), table_name="system_flavors")
    op.drop_index(op.f("ix_system_flavors_code"), table_name="system_flavors")
    op.drop_table("system_flavors")
    op.drop_index(op.f("ix_users_updated_by"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_created_by"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_system_kinds_updated_by"), table_name="system_kinds")
    op.drop_index(op.f("ix_system_kinds_id"), table_name="system_kinds")
    op.drop_index(op.f("ix_system_kinds_created_by"), table_name="system_kinds")
    op.drop_index(op.f("ix_system_kinds_code"), table_name="system_kinds")
    op.drop_table("system_kinds")
    op.drop_index(op.f("ix_credential_refs_updated_by"), table_name="credential_refs")
    op.drop_index(op.f("ix_credential_refs_id"), table_name="credential_refs")
    op.drop_index(op.f("ix_credential_refs_created_by"), table_name="credential_refs")
    op.drop_table("credential_refs")
    # ### end Alembic commands ###
