"""add system flavor

Revision ID: b06e5202aa44
Revises: 2780f975a786
Create Date: 2025-11-11 13:56:25.271342

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b06e5202aa44"
down_revision: Union[str, Sequence[str], None] = "2780f975a786"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "system_flavors",
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("vendor", sa.String(), nullable=True),
        sa.Column("version", sa.String(), nullable=True),
        sa.Column("kind_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["kind_id"],
            ["system_kinds.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_system_flavors_code"), "system_flavors", ["code"], unique=True
    )
    op.create_index(
        op.f("ix_system_flavors_created_by"),
        "system_flavors",
        ["created_by"],
        unique=False,
    )
    op.create_index(op.f("ix_system_flavors_id"), "system_flavors", ["id"], unique=True)
    op.create_index(
        op.f("ix_system_flavors_updated_by"),
        "system_flavors",
        ["updated_by"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_system_flavors_updated_by"), table_name="system_flavors")
    op.drop_index(op.f("ix_system_flavors_id"), table_name="system_flavors")
    op.drop_index(op.f("ix_system_flavors_created_by"), table_name="system_flavors")
    op.drop_index(op.f("ix_system_flavors_code"), table_name="system_flavors")
    op.drop_table("system_flavors")
    # ### end Alembic commands ###
