"""add credential ref

Revision ID: c492bc36b222
Revises: 4ad1f4877a24
Create Date: 2025-11-12 17:57:21.169723

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c492bc36b222"
down_revision: Union[str, Sequence[str], None] = "4ad1f4877a24"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "credential_refs",
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("path", sa.String(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "provider", "path", name="idx_credential_ref_provider_path"
        ),
    )
    op.create_index(
        op.f("ix_credential_refs_created_by"),
        "credential_refs",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_credential_refs_id"), "credential_refs", ["id"], unique=True
    )
    op.create_index(
        op.f("ix_credential_refs_updated_by"),
        "credential_refs",
        ["updated_by"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_credential_refs_updated_by"), table_name="credential_refs")
    op.drop_index(op.f("ix_credential_refs_id"), table_name="credential_refs")
    op.drop_index(op.f("ix_credential_refs_created_by"), table_name="credential_refs")
    op.drop_table("credential_refs")
    # ### end Alembic commands ###
