"""add field

Revision ID: c4cdab559563
Revises: 02f269a5918b
Create Date: 2025-11-15 14:28:20.374560

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c4cdab559563"
down_revision: Union[str, Sequence[str], None] = "02f269a5918b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fields",
        sa.Column("dataset_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("path", sa.Text(), nullable=True),
        sa.Column("pii_tags", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("extra", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["datasets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dataset_id", "name", name="idx_field_dataset_id_name"),
    )
    op.create_index(
        op.f("ix_fields_created_by"), "fields", ["created_by"], unique=False
    )
    op.create_index(op.f("ix_fields_id"), "fields", ["id"], unique=True)
    op.create_index(
        op.f("ix_fields_updated_by"), "fields", ["updated_by"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_fields_updated_by"), table_name="fields")
    op.drop_index(op.f("ix_fields_id"), table_name="fields")
    op.drop_index(op.f("ix_fields_created_by"), table_name="fields")
    op.drop_table("fields")
    # ### end Alembic commands ###
