"""add systems

Revision ID: e105f64cb2ce
Revises: c492bc36b222
Create Date: 2025-11-12 18:04:36.274193

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e105f64cb2ce"
down_revision: Union[str, Sequence[str], None] = "c492bc36b222"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "systems",
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("tags", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("extra", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("flavor_id", sa.UUID(), nullable=False),
        sa.Column("credential_ref_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["credential_ref_id"],
            ["credential_refs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["flavor_id"],
            ["system_flavors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_systems_code"), "systems", ["code"], unique=True)
    op.create_index(
        op.f("ix_systems_created_by"), "systems", ["created_by"], unique=False
    )
    op.create_index(op.f("ix_systems_id"), "systems", ["id"], unique=True)
    op.create_index(
        op.f("ix_systems_updated_by"), "systems", ["updated_by"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_systems_updated_by"), table_name="systems")
    op.drop_index(op.f("ix_systems_id"), table_name="systems")
    op.drop_index(op.f("ix_systems_created_by"), table_name="systems")
    op.drop_index(op.f("ix_systems_code"), table_name="systems")
    op.drop_table("systems")
    # ### end Alembic commands ###
