from __future__ import annotations

import enum
import uuid
from typing import Any

from pydantic import BaseModel, ConfigDict

from aide_schemas.mixins import MetaDataMixin, NoteMixin, VersionedUpdateMixin


class FieldOrigin(str, enum.Enum):
    """Lifecycle state of a Field for lineage purposes.

    MAPPED — has inbound FieldLink(s) as target; fed from a source column.
    TECH — generated by the pipeline (timestamps, CDC op, hashes).
    DEPRECATED — no source, worker pads NULL for backward compatibility.
    """

    MAPPED = "mapped"
    TECH = "tech"
    DEPRECATED = "deprecated"


class FieldBase(BaseModel):
    """Base field schema."""

    dataset_id: uuid.UUID
    parent_id: uuid.UUID | None = None
    name: str
    path: str | None = None
    extra: dict[str, Any] | None = None
    origin: FieldOrigin = FieldOrigin.MAPPED


class FieldCreate(FieldBase, NoteMixin):
    """Schema for field creation."""

    pass


class FieldUpdate(VersionedUpdateMixin, NoteMixin):
    """Schema for field update."""

    dataset_id: uuid.UUID | None = None
    parent_id: uuid.UUID | None = None
    name: str | None = None
    path: str | None = None
    extra: dict[str, Any] | None = None
    origin: FieldOrigin | None = None


class FieldRead(FieldBase, MetaDataMixin):
    """Schema for reading field data."""

    model_config = ConfigDict(from_attributes=True)


class FieldTree(MetaDataMixin):
    """Recursive schema for reading a field tree."""

    model_config = ConfigDict(from_attributes=True)

    dataset_id: uuid.UUID
    parent_id: uuid.UUID | None
    name: str
    path: str | None
    extra: dict[str, Any] | None
    origin: FieldOrigin
    children: list[FieldTree]
